// Code generated by gen.go; DO NOT EDIT.

package opslevel

// AlertSource represents an alert source that is currently integrated and belongs to the account.
type AlertSource struct {
	Description string              `graphql:"description" json:"description"` // The description of the alert source.
	ExternalId  string              `graphql:"externalId" json:"externalId"`   // The external id of the alert.
	Id          ID                  `graphql:"id" json:"id"`                   // The id of the alert source.
	Integration IntegrationId       `graphql:"integration" json:"integration"` // The integration of the alert source.
	Metadata    string              `graphql:"metadata" json:"metadata"`       // The metadata of the alert source.
	Name        string              `graphql:"name" json:"name"`               // The name of the alert source.
	Type        AlertSourceTypeEnum `graphql:"type" json:"type"`               // The type of the alert.
	Url         string              `graphql:"url" json:"url"`                 // The url to the alert source.
}

// AlertSourceService represents an alert source that is connected with a service.
type AlertSourceService struct {
	AlertSource AlertSource               `graphql:"alertSource" json:"alertSource"` // The alert source that is mapped to a service
	Id          ID                        `graphql:"id" json:"id"`                   // id of the alert_source_service mapping.
	Service     ServiceId                 `graphql:"service" json:"service"`         // The service the alert source maps to.
	Status      AlertSourceStatusTypeEnum `graphql:"status" json:"status"`           // The status of the alert source.
}

// Category represents a category is used to group related checks in a rubric.
type Category struct {
	Description string `graphql:"description" json:"description"` // The description of the category.
	Id          ID     `graphql:"id" json:"id"`                   // The unique identifier for the category.
	Name        string `graphql:"name" json:"name"`               // The display name of the category.
}
