# https://taskfile.dev/

version: '3'

tasks:
  ci:
    desc: Workflow to run in CI
    deps: [setup]
    cmds:
      - task: lint
      - task: test

  generate:
    desc: Generate code based on public GraphQL Interface
    aliases: [gen]
    cmds:
      - go generate
      - gofumpt -w .

  lint:
    desc: Formatting and linting
    cmds:
      - test -z "$(gofumpt -d -e . | tee /dev/stderr)"
      - go vet ./...
      - golangci-lint run

  fix:
    desc: Fix formatting and linting
    cmds:
      - gofumpt -w .
      - go mod tidy
      - golangci-lint run --fix

  setup:
    desc: Setup linter, formatter, etc. for local testing and CI
    cmds:
      - task: install-go-tool
        vars: { GO_TOOL: "gofumpt", GO_TOOL_PATH: "mvdan.cc/gofumpt@latest" }
      - task: install-go-tool
        vars: { GO_TOOL: "golangci-lint", GO_TOOL_PATH: "github.com/golangci/golangci-lint/cmd/golangci-lint@latest" }

  test:
    desc: Run tests
    cmds:
      - go test -race -coverprofile=coverage.out -covermode=atomic -v ./... {{ .CLI_ARGS }}
      - grep -v "/enum.go" coverage.out > coverage.txt
    silent: true

  # internal (not directly called) tasks

  install-go-tool:
    internal: true
    silent: true
    vars:
      IS_TOOL_INSTALLED:
        sh: which {{.GO_TOOL}} > /dev/null || echo "1"
    cmds:
      - test -z "{{.IS_TOOL_INSTALLED}}" || echo "Installing {{.GO_TOOL}}..."
      - test -z "{{.IS_TOOL_INSTALLED}}" || go install {{.GO_TOOL_PATH}}
      - test -n $(go env GOBIN) || go env -w GOBIN=$(go env GOPATH)/bin
      - echo "  '{{.GO_TOOL}}' is installed."
    requires:
      vars: [GO_TOOL, GO_TOOL_PATH]
