# https://taskfile.dev/

version: '3'

tasks:
  generate:
    desc: Generate code based on public GraphQL Interface
    cmds:
      - go generate
      - gofumpt -w .

  install-gofumpt:
    desc: go install "gofumpt" and set GOBIN if not set
    silent: true
    vars:
      IS_GOFUMPT_INSTALLED:
        sh: which gofumpt > /dev/null || echo "1"
    cmds:
      - test -z "{{.IS_GOFUMPT_INSTALLED}}" || echo "Installing gofumpt..."
      - test -z "{{.IS_GOFUMPT_INSTALLED}}" || go install mvdan.cc/gofumpt@latest
      - test -n $(go env GOBIN) || go env -w GOBIN=$(go env GOPATH)/bin

  lint:
    desc: Formatting and linting
    deps: [install-gofumpt]
    cmds:
      - gofumpt -d .
      - go vet ./...
      - golangci-lint run

  lintfix:
    desc: Fix formatting and linting
    deps: [install-gofumpt]
    cmds:
      - gofumpt -w .
      - go mod tidy
      - golangci-lint run --fix

  test:
    desc: Run tests
    cmds:
      - go test -v -cover -race ./... {{ .CLI_ARGS }}
    silent: true
