# https://taskfile.dev/

version: '3'

tasks:
  generate:
    desc: Generate code based on public GraphQL Interface
    cmds:
      - go generate
      - gofmt -w .
  lint:
    desc: Formatting and linting
    cmds:
      - gofmt -d .
      - go vet ./...
      - golangci-lint run

  lintfix:
    desc: Fix formatting and linting
    cmds:
      - gofmt -w .
      - go mod tidy
      - golangci-lint run --fix

  test:
    desc: Run tests
    cmds:
      - go test -v ./... {{ .CLI_ARGS }}
    silent: true
