name: Dependabot Labels

on:
  pull_request:
    types:
      - labeled

jobs:
  dependabot-pr-label:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    uses: OpsLevel/actions/.github/workflows/dependabot_pr_labels.yml@main
