name: Security
permissions:
  contents: read

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * 1"  # 8am CT on Mondays

jobs:
  call-grype:
    uses: opslevel/actions/.github/workflows/grype.yml@d66c9d7c93ff6df99a929e012366433e564d58fa # main
    with:
      alias: opslevel-go
    secrets: inherit
