name: "Snyk"

on: 
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Snyk Test
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: "--prune-repeated-subdependencies --json | ./snyk_report.json"
    - name: Report To OpsLevel
      run: |
        curl -X POST ${{ secrets.OL_SNYK_INTEGRATION_URL }} -H 'content-type: application/json' --data-binary ./snyk_report.json
